### ISSUE TITLE
Configurable + automatic indicator position relative to stack

### ISSUE THREAD

**Issue by AdamWagner** [AdamWagner/stackline#10]
Configuration ideas:

**Indicator position relative to stack:**

1. Top/bottom
2. Left/right
3. Inside/outside

**Indicator position offset relative to stack:**

- top offset
- bottom offset
- left offset
- right offset 

Values may be negative.

Declarations may be combined to achieve [@alin23](gh-alin23)'s [mockup here](https://github.com/koekeishiya/yabai/issues/203#issuecomment-652948362) with indicators that are centered on the edge of window and occlude a small amount of the window content.

**Automagic™ positioning**

Automatically position indicators on the _outside edge of the stack_ nearest the edge of the screen. This would be nice for users who use small or no window gaps and modest screen padding.

**Comment by AdamWagner** [comment]
Examples for configuration variable names / values from @alin23

```sh
stack_dock_top_offset 0
stack_dock_top_offset 5%
stack_dock_top_offset 10%
```

**Comment by AdamWagner** [comment]
Somewhat addressed by window offset config settings in: https://github.com/AdamWagner/stackline/pull/18/commits/c30e8556950b1dc39b21ea96009063edde475dcd#diff-8aa92ecfa197cc600dd2ac0ef22d3fb9R58

**Comment by grozan** [comment]
besides the default "smart" positioning, could we still get the option to force the position of the indicators to always be `top`, `bottom`, `left` or `right` please?
Thanks
