### ISSUE TITLE
Stackline icon not clickable with my multi-monitor layout

### ISSUE THREAD

**Issue by snakewa** [AdamWagner/stackline#62]
Red arrow is the click point.
Purple border is the icon area.
Blue Border shows that actually I put my MacBook in front of my monitor and MacBook own the system topbar so I found the coordinate of the click is kind of negative value. So the hittest might fail because of this.
![image](https://user-images.githubusercontent.com/83506/103930236-6433fd00-5159-11eb-9a70-19247746a303.png)

If I move the system top bar to the external monitor, then the icon could be clicked but still offset (less accuracy of icon frame and click point)

macOS: bigSur 11.0.1 (20B29)
version: 

commit 8c1533ea71e9af3315edb889a6a44e7cc5723f16 (HEAD -> master, origin/master, origin/HEAD)
Author: Jerred Shepherd <ShepherdJerred@gmail.com>
Date:   Sat Dec 12 13:25:06 2020 -0800

    Fix link (#54)

**Comment by AdamWagner** [comment]
@snakewa I think that this is fixed in https://github.com/AdamWagner/stackline/pull/81

(the offset issue was [fixed in an earlier commit](https://github.com/AdamWagner/stackline/commit/215b35d383a6d120e9969415d4b6c29bde0cac81))

Apologies for the long wait. Would still be great to know if this this fix works for you ;-)

**Comment by pomdtr** [comment]
I still encounter the issue with a two monitor layout (clicking icon switch the app in the wrong display)
